### PR TITLE
add eslint + rules to package.json

### PR DESCRIPTION
**Pull request by mLuby**
@armandopmj added a ton of rules. 

Big question for you is whether you want to bit the bullet and start using `let` over `var` and `() => {}` ES6 arrows when appropriate. Let me know either way and I'll configure it.

The next commit here will be me making the existing code pass.

### CODE REVIEW

**Comment by armandopmj** [comment]
@mLuby Awesome, ill review the rules more in depth after finishing up some more work but it looks good so far.  Hmm lets use this project as a way to become well versed in ES6...  so lets use `let` and the arrow syntax.  I still have yet to fully review ES6 syntax so let me know if any subsequent PRs have syntax that can be rewritten following ES6.

**Comment by mLuby** [comment]
3 files left with `// TODO LINTING NOT DONE`
As you can see, lots of changes.
I have a feeling this noticed some parts that weren't actually working properly. We'll see what happens when the server starts up! :fire:

**Comment by mLuby** [comment]
okay @armandopmj this PR is ready for review (and merge if it's good). I manually confirmed that the 3 API paths mentioned in [the README](https://github.com/projectLiftOff/surpriseHer.server/blob/linting/README.md) work end-to-end.

**Comment by armandopmj** [comment]
@mLuby spent most of the recovering and reading about ES6... dude JS just got a whole lot more powerful!!  Shit is awesome!

**Comment by mLuby** [comment]
yeah, welcome to the bleeding edge!

**Pull request merged**
