### PR TITLE
ToS page (without actual copy yet)

### PR DESCRIPTION
**Pull request by mLuby**
@armandopmj there's a big move in commit 1

### CODE REVIEW

**Comment by armandopmj** [comment]
@mLuby fix conflicts

**Comment by mLuby** [comment]
oh right

**Comment by mLuby** [comment]
@armandopmj rebased onto master so should be review for code review and merge. It's a little hard to finish without having the copy but we can add that whenever it's ready.

screen shot 2015-12-06 at 21 23 43

**Comment by mLuby** [comment]
closes #45 #63 #64

**Comment by armandopmj** [comment]
@mLuby looks good!!

**Pull request merged**
